# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7a35tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir E:/Lab_DL/Flappy_Bird_demo/project_1/project_1.cache/wt [current_project]
set_property parent.project_path E:/Lab_DL/Flappy_Bird_demo/project_1/project_1.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo e:/Lab_DL/Flappy_Bird_demo/project_1/project_1.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files E:/javaproject/coe/coe_convert/bg.coe
add_files E:/javaproject/coe/coe_convert/bird.coe
add_files E:/javaproject/coe/coe_convert/tube_head.coe
add_files E:/javaproject/coe/coe_convert/tube_body.coe
read_verilog -library xil_defaultlib {
  E:/Lab_DL/Flappy_Bird_demo/project_1/project_1.srcs/sources_1/new/bird_pos.v
  E:/Lab_DL/Flappy_Bird_demo/project_1/project_1.srcs/sources_1/new/clk_div.v
  E:/Lab_DL/Flappy_Bird_demo/project_1/project_1.srcs/sources_1/new/converter.v
  E:/Lab_DL/Flappy_Bird_demo/project_1/project_1.srcs/sources_1/new/display.v
  E:/Lab_DL/Flappy_Bird_demo/project_1/project_1.srcs/sources_1/new/is_bird.v
  E:/Lab_DL/Flappy_Bird_demo/project_1/project_1.srcs/sources_1/new/is_tube.v
  E:/Lab_DL/Flappy_Bird_demo/project_1/project_1.srcs/sources_1/new/random_gen.v
  E:/Lab_DL/Flappy_Bird_demo/project_1/project_1.srcs/sources_1/new/segment.v
  E:/Lab_DL/Flappy_Bird_demo/project_1/project_1.srcs/sources_1/new/Main.v
}
read_ip -quiet E:/Lab_DL/Flappy_Bird_demo/project_1/project_1.srcs/sources_1/ip/BG_png/BG_png.xci
set_property used_in_implementation false [get_files -all e:/Lab_DL/Flappy_Bird_demo/project_1/project_1.srcs/sources_1/ip/BG_png/BG_png_ooc.xdc]

read_ip -quiet E:/Lab_DL/Flappy_Bird_demo/project_1/project_1.srcs/sources_1/ip/Bird_png/Bird_png.xci
set_property used_in_implementation false [get_files -all e:/Lab_DL/Flappy_Bird_demo/project_1/project_1.srcs/sources_1/ip/Bird_png/Bird_png_ooc.xdc]

read_ip -quiet E:/Lab_DL/Flappy_Bird_demo/project_1/project_1.srcs/sources_1/ip/TubeHead_png/TubeHead_png.xci
set_property used_in_implementation false [get_files -all e:/Lab_DL/Flappy_Bird_demo/project_1/project_1.srcs/sources_1/ip/TubeHead_png/TubeHead_png_ooc.xdc]

read_ip -quiet E:/Lab_DL/Flappy_Bird_demo/project_1/project_1.srcs/sources_1/ip/TubeBody_png/TubeBody_png.xci
set_property used_in_implementation false [get_files -all e:/Lab_DL/Flappy_Bird_demo/project_1/project_1.srcs/sources_1/ip/TubeBody_png/TubeBody_png_ooc.xdc]

read_ip -quiet E:/Lab_DL/Flappy_Bird_demo/project_1/project_1.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci
set_property used_in_implementation false [get_files -all e:/Lab_DL/Flappy_Bird_demo/project_1/project_1.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_board.xdc]
set_property used_in_implementation false [get_files -all e:/Lab_DL/Flappy_Bird_demo/project_1/project_1.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xdc]
set_property used_in_implementation false [get_files -all e:/Lab_DL/Flappy_Bird_demo/project_1/project_1.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc E:/Lab_DL/Flappy_Bird_demo/project_1/project_1.srcs/constrs_1/new/xdcc.xdc
set_property used_in_implementation false [get_files E:/Lab_DL/Flappy_Bird_demo/project_1/project_1.srcs/constrs_1/new/xdcc.xdc]


synth_design -top Main -part xc7a35tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef Main.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file Main_utilization_synth.rpt -pb Main_utilization_synth.pb"
