set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports {B[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {B[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {B[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {B[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {G[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {G[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {G[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {G[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {R[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {R[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {R[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {R[0]}]
set_property PACKAGE_PIN P17 [get_ports clk]
set_property PACKAGE_PIN C7 [get_ports {B[0]}]
set_property PACKAGE_PIN E6 [get_ports {B[1]}]
set_property PACKAGE_PIN E5 [get_ports {B[2]}]
set_property PACKAGE_PIN E7 [get_ports {B[3]}]
set_property PACKAGE_PIN B6 [get_ports {G[0]}]
set_property PACKAGE_PIN A6 [get_ports {G[1]}]
set_property PACKAGE_PIN A5 [get_ports {G[2]}]
set_property PACKAGE_PIN D8 [get_ports {G[3]}]
set_property PACKAGE_PIN F5 [get_ports {R[0]}]
set_property PACKAGE_PIN C6 [get_ports {R[1]}]
set_property PACKAGE_PIN C5 [get_ports {R[2]}]
set_property PACKAGE_PIN B7 [get_ports {R[3]}]
set_property PACKAGE_PIN D7 [get_ports hsync]
set_property PACKAGE_PIN C4 [get_ports vsync]
set_property PACKAGE_PIN P15 [get_ports rst]

set_property IOSTANDARD LVCMOS33 [get_ports hsync]
set_property IOSTANDARD LVCMOS33 [get_ports rst]
set_property IOSTANDARD LVCMOS33 [get_ports vsync]


set_property PACKAGE_PIN R1 [get_ports {sw[0]}]
set_property PACKAGE_PIN N4 [get_ports {sw[1]}]
set_property PACKAGE_PIN M4 [get_ports {sw[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sw[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sw[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sw[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports restart]
set_property PACKAGE_PIN V1 [get_ports restart]


set_property IOSTANDARD LVCMOS33 [get_ports flap]
set_property PACKAGE_PIN U4 [get_ports flap]

set_property PACKAGE_PIN T5 [get_ports cheatmode]
set_property IOSTANDARD LVCMOS33 [get_ports cheatmode]

set_property IOSTANDARD LVCMOS33 [get_ports {crashflag[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {crashflag[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {crashflag[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {crashflag[0]}]
set_property PACKAGE_PIN K2 [get_ports {crashflag[0]}]
set_property PACKAGE_PIN J2 [get_ports {crashflag[1]}]
set_property PACKAGE_PIN J3 [get_ports {crashflag[2]}]
set_property PACKAGE_PIN H4 [get_ports {crashflag[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports cheatled]
set_property PACKAGE_PIN K3 [get_ports cheatled]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets restart_IBUF]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets reso_IBUF]

set_property IOSTANDARD LVCMOS33 [get_ports overled]
set_property PACKAGE_PIN K2 [get_ports overled]

set_property IOSTANDARD LVCMOS33 [get_ports {cho[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cho[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cho[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cho[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cho[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cho[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cho[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cho[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lseg[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lseg[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lseg[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lseg[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lseg[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lseg[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lseg[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lseg[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rseg[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rseg[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rseg[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rseg[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rseg[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rseg[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rseg[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rseg[0]}]
set_property PACKAGE_PIN G6 [get_ports {cho[0]}]
set_property PACKAGE_PIN E1 [get_ports {cho[1]}]
set_property PACKAGE_PIN F1 [get_ports {cho[2]}]
set_property PACKAGE_PIN G1 [get_ports {cho[3]}]
set_property PACKAGE_PIN H1 [get_ports {cho[4]}]
set_property PACKAGE_PIN C1 [get_ports {cho[5]}]
set_property PACKAGE_PIN C2 [get_ports {cho[6]}]
set_property PACKAGE_PIN G2 [get_ports {cho[7]}]
set_property PACKAGE_PIN B4 [get_ports {lseg[0]}]
set_property PACKAGE_PIN A4 [get_ports {lseg[1]}]
set_property PACKAGE_PIN A3 [get_ports {lseg[2]}]
set_property PACKAGE_PIN B1 [get_ports {lseg[3]}]
set_property PACKAGE_PIN A1 [get_ports {lseg[4]}]
set_property PACKAGE_PIN B3 [get_ports {lseg[5]}]
set_property PACKAGE_PIN B2 [get_ports {lseg[6]}]
set_property PACKAGE_PIN D5 [get_ports {lseg[7]}]
set_property PACKAGE_PIN D4 [get_ports {rseg[0]}]
set_property PACKAGE_PIN E3 [get_ports {rseg[1]}]
set_property PACKAGE_PIN D3 [get_ports {rseg[2]}]
set_property PACKAGE_PIN F4 [get_ports {rseg[3]}]
set_property PACKAGE_PIN F3 [get_ports {rseg[4]}]
set_property PACKAGE_PIN E2 [get_ports {rseg[5]}]
set_property PACKAGE_PIN D2 [get_ports {rseg[6]}]
set_property PACKAGE_PIN H2 [get_ports {rseg[7]}]

set_property IOSTANDARD LVCMOS33 [get_ports reso]
set_property PACKAGE_PIN P3 [get_ports reso]

set_property IOSTANDARD LVCMOS33 [get_ports stateled]
set_property PACKAGE_PIN G3 [get_ports stateled]
